#!/usr/bin/env python3
"""在本地触发 GitHub Action，并把结果缓存同步回 WDC。

触发与结果读取全部使用 Git/SSH，不依赖 GitHub API token：
1. 通过 SSH 在 WDC 计算到期 YouTube ID；
2. 写入 ``youtube_targets.txt`` 并用 SSH Git 推送，触发 Action；
3. 轮询 ``youtube-action-cache`` 分支上的 payload；
4. 通过 SSH 将 payload 交给 WDC 合并缓存。
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET_PATH = ROOT / "youtube_targets.txt"
REPO_SSH = "git@github.com:Marica7731/yt-comment-automation.git"
CACHE_BRANCH = "youtube-action-cache"
PAYLOAD_PATH = "youtube-action-payload.json"
VIDEO_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")


def _run(args: list[str], input_bytes: bytes | None = None) -> bytes:
    result = subprocess.run(
        args,
        cwd=ROOT,
        input=input_bytes,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(detail or f"command failed: {' '.join(map(str, args))}")
    return result.stdout


def _returncode(args: list[str]) -> int:
    return subprocess.run(
        args,
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        check=False,
    ).returncode


def _ssh(command: str, input_bytes: bytes | None = None) -> bytes:
    return _run(
        ["ssh", "-o", "BatchMode=yes", "vps-wdc", command],
        input_bytes=input_bytes,
    )


def _due_targets(refresh: bool) -> list[str]:
    command = (
        "cd /opt/yt-comment-automation && "
        "DATA_DIR=/opt/yt-comment-automation/data "
        "python3 -m yt_comment_automation.youtube_targets"
    )
    if refresh:
        command += " --refresh"
    output = json.loads(_ssh(command).decode("utf-8"))
    if not isinstance(output, list) or not all(isinstance(item, str) for item in output):
        raise RuntimeError("youtube_targets 返回值不是字符串数组")
    invalid = [item for item in output if not VIDEO_ID_RE.fullmatch(item)]
    if invalid:
        raise RuntimeError(f"youtube_targets 返回了非法视频 ID: {invalid}")
    return list(dict.fromkeys(output))


def _render_targets(video_ids: list[str], generated_at: str) -> str:
    return (
        "# generated by dev/run_youtube_action.py\n"
        f"# generated_at={generated_at}\n"
        f"{','.join(video_ids)}\n"
    )


def _commit_and_push_targets() -> tuple[str, str]:
    if _returncode(["git", "diff", "--cached", "--quiet"]) != 0:
        raise RuntimeError("Git index 已有其他暂存变更，拒绝提交 YouTube 目标")
    relative_target = TARGET_PATH.relative_to(ROOT)
    if _run(["git", "status", "--short", "--", relative_target]):
        _run(["git", "add", "--", relative_target])
        _run(
            [
                "git",
                "commit",
                "-m",
                "chore: queue YouTube Action targets",
                "--",
                relative_target,
            ]
        )
    previous_cache_head = _cache_head(required=False)
    head = _run(["git", "rev-parse", "HEAD"]).decode().strip()
    _run(["git", "push", REPO_SSH, "HEAD:master"])
    return head, previous_cache_head


def _cache_head(required: bool = True) -> str:
    output = _run(
        ["git", "ls-remote", REPO_SSH, f"refs/heads/{CACHE_BRANCH}"]
    ).decode()
    head = output.split()[0] if output.split() else ""
    if required and not head:
        raise RuntimeError(f"远端不存在 {CACHE_BRANCH} 分支")
    return head


def _wait_for_payload(
    previous_head: str,
    video_ids: list[str],
    timeout_seconds: float,
    poll_seconds: float,
) -> tuple[dict, str]:
    deadline = time.monotonic() + timeout_seconds
    last_head = previous_head
    while time.monotonic() < deadline:
        current_head = _cache_head(required=False)
        if current_head and current_head != previous_head and current_head != last_head:
            last_head = current_head
            _run(
                [
                    "git",
                    "fetch",
                    "--quiet",
                    "--no-tags",
                    REPO_SSH,
                    f"refs/heads/{CACHE_BRANCH}",
                ]
            )
            raw = _run(["git", "show", f"FETCH_HEAD:{PAYLOAD_PATH}"])
            payload = json.loads(raw.decode("utf-8"))
            if payload.get("video_ids") == video_ids:
                return payload, current_head
        time.sleep(poll_seconds)
    raise RuntimeError(
        f"{timeout_seconds:.0f} 秒内未读取到匹配 {len(video_ids)} 个目标的 Action payload"
    )


def _sync_to_wdc(payload: dict) -> dict:
    encoded = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    _ssh("umask 077; cat > /tmp/youtube-action-payload.json", encoded)
    output = _ssh(
        "cd /opt/yt-comment-automation && "
        "DATA_DIR=/opt/yt-comment-automation/data "
        "python3 -m yt_comment_automation.youtube_cache_sync "
        "/tmp/youtube-action-payload.json"
    )
    summary = json.loads(output.decode("utf-8"))
    if not isinstance(summary, dict):
        raise RuntimeError("youtube_cache_sync 返回值不是 JSON object")
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="触发 GitHub Action 抓取 YouTube 并同步 WDC 缓存"
    )
    parser.add_argument(
        "--no-refresh",
        action="store_true",
        help="不刷新 WDC 的 B 站合集快照",
    )
    parser.add_argument("--timeout", type=float, default=1800.0)
    parser.add_argument("--poll-interval", type=float, default=5.0)
    args = parser.parse_args(argv)
    if args.timeout <= 0 or args.poll_interval <= 0:
        parser.error("--timeout 和 --poll-interval 必须大于 0")

    video_ids = _due_targets(refresh=not args.no_refresh)
    if not video_ids:
        print(json.dumps({"video_ids": 0, "action": "skipped"}, ensure_ascii=False))
        return 0

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    TARGET_PATH.write_text(_render_targets(video_ids, generated_at), encoding="utf-8")
    pushed_commit, previous_cache_head = _commit_and_push_targets()
    payload, cache_commit = _wait_for_payload(
        previous_cache_head,
        video_ids,
        timeout_seconds=args.timeout,
        poll_seconds=args.poll_interval,
    )
    synced = _sync_to_wdc(payload)
    failures = payload.get("failures") or []
    summary = {
        "generated_at": generated_at,
        "pushed_commit": pushed_commit,
        "cache_commit": cache_commit,
        "video_ids": len(video_ids),
        "fetched": len(payload.get("results") or {}),
        "failures": failures,
        "sync": synced,
    }
    print(json.dumps(summary, ensure_ascii=False))
    return 1 if failures else 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, ValueError, json.JSONDecodeError) as err:
        print(json.dumps({"error": str(err)}, ensure_ascii=False), file=sys.stderr)
        sys.exit(1)
