import json

import pytest

from dev import run_youtube_action as runner


def test_render_targets_has_timestamp_and_comma_separated_ids():
    rendered = runner._render_targets(
        ["abcdefghijk", "lmnopqrstuv"],
        "2026-10-02T12:00:00+00:00",
    )
    assert rendered.splitlines() == [
        "# generated by dev/run_youtube_action.py",
        "# generated_at=2026-10-02T12:00:00+00:00",
        "abcdefghijk,lmnopqrstuv",
    ]


def test_due_targets_rejects_invalid_ids(monkeypatch):
    monkeypatch.setattr(runner, "_ssh", lambda command: json.dumps(["bad-id"]).encode())
    with pytest.raises(RuntimeError, match="非法视频 ID"):
        runner._due_targets(refresh=False)


def test_wait_for_payload_accepts_only_matching_action_result(monkeypatch):
    video_ids = ["abcdefghijk"]
    payload = {"video_ids": video_ids, "results": {}}
    heads = iter(["old", "new", "new"])
    monkeypatch.setattr(runner, "_cache_head", lambda required=True: next(heads))
    monkeypatch.setattr(runner.time, "sleep", lambda seconds: None)

    def fake_run(args, input_bytes=None):
        if "fetch" in args:
            return b""
        if "show" in args:
            return json.dumps(payload).encode()
        raise AssertionError(args)

    monkeypatch.setattr(runner, "_run", fake_run)
    result, head = runner._wait_for_payload(
        "old",
        video_ids,
        timeout_seconds=1,
        poll_seconds=0,
    )
    assert result == payload
    assert head == "new"


def test_wait_for_payload_times_out_when_cache_branch_is_unchanged(monkeypatch):
    monkeypatch.setattr(runner, "_cache_head", lambda required=True: "old")
    monkeypatch.setattr(runner.time, "sleep", lambda seconds: None)
    with pytest.raises(RuntimeError, match="未读取到匹配"):
        runner._wait_for_payload(
            "old",
            ["abcdefghijk"],
            timeout_seconds=0.01,
            poll_seconds=0,
        )


def test_workflow_uses_push_trigger_secret_and_three_second_gap():
    workflow = (
        runner.ROOT / ".github" / "workflows" / "fetch-youtube.yml"
    ).read_text(encoding="utf-8")
    assert "paths:\n      - youtube_targets.txt" in workflow
    assert "YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}" in workflow
    assert 'YOUTUBE_REQUEST_MIN_GAP_SECONDS: "3"' in workflow
    assert "push -q origin HEAD:youtube-action-cache" in workflow
